
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.3 EDK_MS3.70d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_MDM_0_DEVICE_ID,
		XPAR_MDM_0_BASEADDR,
		XPAR_MDM_0_BAUDRATE,
		XPAR_MDM_0_USE_PARITY,
		XPAR_MDM_0_ODD_PARITY,
		XPAR_MDM_0_DATA_BITS
	},
	{
		XPAR_MSP430_UART_DEVICE_ID,
		XPAR_MSP430_UART_BASEADDR,
		XPAR_MSP430_UART_BAUDRATE,
		XPAR_MSP430_UART_USE_PARITY,
		XPAR_MSP430_UART_ODD_PARITY,
		XPAR_MSP430_UART_DATA_BITS
	},
	{
		XPAR_USB_UART_DEVICE_ID,
		XPAR_USB_UART_BASEADDR,
		XPAR_USB_UART_BAUDRATE,
		XPAR_USB_UART_USE_PARITY,
		XPAR_USB_UART_ODD_PARITY,
		XPAR_USB_UART_DATA_BITS
	}
};


