
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.3 EDK_MS3.70d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_CS_PUSH_3BIT_DEVICE_ID,
		XPAR_CS_PUSH_3BIT_BASEADDR,
		XPAR_CS_PUSH_3BIT_INTERRUPT_PRESENT,
		XPAR_CS_PUSH_3BIT_IS_DUAL
	},
	{
		XPAR_LEDS_4BIT_DEVICE_ID,
		XPAR_LEDS_4BIT_BASEADDR,
		XPAR_LEDS_4BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_4BIT_IS_DUAL
	}
};


