
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.3 EDK_MS3.70d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_TEMP_SENSOR_DEVICE_ID,
		XPAR_TEMP_SENSOR_BASEADDR,
		XPAR_TEMP_SENSOR_TEN_BIT_ADR,
		XPAR_TEMP_SENSOR_GPO_WIDTH
	}
};


